
spring:
  application:
    name: spring-cloud-rpc-consumer
server:
  port: 9001
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
